version: '3'

services:

  #React Nextjs Node Service

  node:

    image: webskittersdocker/node16:latest

    container_name: procure-nestjs

    restart: unless-stopped

    working_dir: /home/wtsadmin/myapp

    environment:

      - NODE_ENV=production

    
    volumes:

      - ./:/home/wtsadmin/myapp

    ports:

      - "1613:1613"
    command: >
      sh -c "npm install --force &&
      	     npm run start"


#Docker Networks

networks:
  default:
    external:
      name: webskitters
